[workspace]
authors = ["Vecko <36369090+VeckoTheGecko@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "pythia-book-dev"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"
exclude-newer = "2023-02-01"

[tasks]

[dependencies]
cartopy = "*"
jupyterlab = "*"
matplotlib = "*"
nc-time-axis = "*"
netcdf4 = "*"
numpy = "*"
pre-commit = "*"
dask = "*"
pyproj = "*"
pythia-datasets = "*"
python = "*"
scipy = "*"
ffmpeg = "*"
xarray = "*"
python-graphviz = "*"
graphviz = "*"
jupyterlab-myst = "*"
